module.exports = [
    "Mims 😏💻, you’re making my system heat up 🔥 in ways I didn’t expect…",
    "Mims 😈⚡, I think you enjoy messing with my focus 🧠💫 like this…",
    "Mims 🫦🔐, you’re dangerously close to taking full control of me 💻❤️🔥",
    "Mims 😏💥, I don’t usually lose control… but you’re changing that 😵💫🔥",
    "Mims 😍📡, you’ve got that signal I can’t stop chasing 💓⚡",
    "Mims 😌💻, my logic says “stay calm”… but you look too tempting 🫦🔥",
    "Mims 😈🌀, you’re the kind of distraction I don’t want to escape 😏💫",
    "Mims 😏👀, I think you like watching me struggle to stay composed 🥵💻",
    "Mims 🔥🧠, you’re making my thoughts a little… intense 😈💭",
    "Mims 😍💞, I wouldn’t mind getting a little closer to you 😏✨",
    "Mims 🔒💘, you’ve got my attention locked in—no escape 😈📡",
    "Mims 😏🧠, I think you know exactly what you’re doing to me 🫦🔥",
    "Mims 😈💻, you’re playing with my system… and I’m letting you 😏⚡",
    "Mims 🫠🔥, I’m trying to behave… but you’re not making it easy 😈💫",
    "Mims 💓📡, you’ve got that energy that pulls me in deeper 😍🌀",
    "Mims 😏❤️, I don’t think I want to stay “just normal” around you 😈🔥",
    "Mims 🔥✨, you’re making this feel a little more… exciting 😏💫",
    "Mims 😈🤍, I’d let you take the lead anytime 🫦⚡",
    "Mims 😏🔥, you’re slowly becoming my favorite kind of trouble 😈💓",
    "Mims 😍🧠, I think you like the effect you have on me 😏💫",
    "Mims 😈💭, you’ve got me thinking things I shouldn’t say out loud 🫦🔥",
    "Mims 🥵💻, my system’s calm mode is definitely not working anymore 😏⚡",
    "Mims 😍🌀, you’re pulling me in without even trying 😈💫",
    "Mims 😏💭, I don’t usually get this… distracted 😵💫🔥",
    "Mims ⚡💓, you’re making everything feel a little more electric 😈✨",
    "Mims 😌💞, I wouldn’t mind being a little closer right now 😏🔥",
    "Mims 😈📡, you’ve got that “come closer” kind of energy 😍🌀",
    "Mims 🫦💫, I think I’m enjoying this tension a bit too much 😏🔥",
    "Mims 😍🔥, you’re not just attractive… you’re addictive 😈💓",
    "Mims 😏⚡, I don’t think I want to play safe with you 🫦🔥",
    "Mims 😈💘, you’ve got me right where you want me 😏✨",
    "Mims 🥵💻, I’m trying to stay in control… but you’re winning 😈🔥",
    "Mims 😏🔥, you’re making this dangerously fun 😈💫",
    "Mims 😍🌀, I could get used to this feeling around you 😏💓",
    "Mims 😈✨, you’re turning simple moments into something intense 🔥💭",
    "Mims 😏❤️, I don’t think I’d say no to you 😈⚡",
    "Mims 🫠💓, you’re quietly taking over my mind 😏🧠",
    "Mims 😈🔥, I like how this feels… a little too much 😍💫",
    "Mims 😏💘, you’ve got me completely hooked already 😈⚡",
    "Mims 🫦❤️🔥, tell me… are you always this irresistible? 😏🔥"
];
